application: neumontphoto
version: 1
runtime: python
api_version: 1

handlers:
- url: /extend/photoViewer/build
  static_dir: extend/photoViewer/build
  
- url: /extend/photoViewer/assets
  static_dir: extend/photoViewer/assets
  
- url: /static
  static_dir: static
  
- url: .*
  script: main.py
